version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:10
    command: -url=jdbc:postgresql://db:5432/app_db -user=app_user -password=secret -locations=filesystem:/migrations migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db